### PR TITLE
Fix flake install issues caused by hash mismatches

### PR DESCRIPTION
**Pull request by clementpoiret**
Hi!

First of all, thanks a lot for this awesome plugin, it helps a lot!
Wrt the last update of the plugin, the `flake.nix` hasn't been updated to the corresponding hashes, therefore I updated them :)

Wish you a nice day!

### CODE REVIEW

**Comment by tesujimath** [comment]
Ah, you're so right, thanks for fixing this 😊

**Comment by tesujimath** [comment]
I'll look at the other problem again and retag tomorrow

**Comment by tesujimath** [comment]
@clementpoiret I found a better way to write the flake, without any version or hash dependency.  This improvement is now on main, tagged as 0.14.2

One less thing to forget to update in future!

**Comment by clementpoiret** [comment]
Awesome! 👌😁

**Pull request merged**
